### ISSUE TITLE
Installation failed on WIndows

### ISSUE THREAD

**Issue by sarwart** [daducci/AMICO#102]
Hi! 

I want to use COMMIT which requires installation of AMICO as prerequisite.  I have tried installing AMICO multiple times with multiple python version but it always fail with the following error. I have tried installing visual studio and C++ build tools multiple time but AMICO installation was never successful. Can you please help in installing these packages

```
 ERROR: Command errored out with exit status 1:
   command: 'd:\rishabh\evaluation\commit-master\venv2\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tabinda\\AppData\\Local\\Temp\\pip-ins
tall-bl2yrzd2\\python-spams_b12ffab79a274d1cafe670f4dc475ade\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tabinda\\AppData\\Local\\Temp\\pip-install-bl2yrzd2\\python-spams_b12ffab79a274d1c
afe670f4dc475ade\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec
'"'"'))' bdist_wheel -d 'C:\Users\Tabinda\AppData\Local\Temp\pip-wheel-m9ghfyhr'
       cwd: C:\Users\Tabinda\AppData\Local\Temp\pip-install-bl2yrzd2\python-spams_b12ffab79a274d1cafe670f4dc475ade\
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\myscipy_rand
  copying myscipy_rand\myscipy_rand.py -> build\lib.win-amd64-3.7\myscipy_rand
  copying myscipy_rand\__init__.py -> build\lib.win-amd64-3.7\myscipy_rand
  creating build\lib.win-amd64-3.7\spams
  copying spams\spams.py -> build\lib.win-amd64-3.7\spams
  copying spams\__init__.py -> build\lib.win-amd64-3.7\spams
  creating build\lib.win-amd64-3.7\spams_wrap
  copying spams_wrap\spams_wrap.py -> build\lib.win-amd64-3.7\spams_wrap
  copying spams_wrap\__init__.py -> build\lib.win-amd64-3.7\spams_wrap
  running egg_info
  writing python_spams.egg-info\PKG-INFO
  writing dependency_links to python_spams.egg-info\dependency_links.txt
  writing requirements to python_spams.egg-info\requires.txt
  writing top-level names to python_spams.egg-info\top_level.txt
  reading manifest file 'python_spams.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'python_spams.egg-info\SOURCES.txt'
  copying spams_wrap\spams.h -> build\lib.win-amd64-3.7\spams_wrap
  copying spams_wrap\spams_wrap.cpp -> build\lib.win-amd64-3.7\spams_wrap
  creating build\lib.win-amd64-3.7\spams_wrap\decomp
  copying spams_wrap\decomp\decomp.h -> build\lib.win-amd64-3.7\spams_wrap\decomp
  copying spams_wrap\decomp\lsqsplx.h -> build\lib.win-amd64-3.7\spams_wrap\decomp
  copying spams_wrap\decomp\projsplx.h -> build\lib.win-amd64-3.7\spams_wrap\decomp
  creating build\lib.win-amd64-3.7\spams_wrap\dictLearn
  copying spams_wrap\dictLearn\arch.h -> build\lib.win-amd64-3.7\spams_wrap\dictLearn
  copying spams_wrap\dictLearn\dicts.h -> build\lib.win-amd64-3.7\spams_wrap\dictLearn
  creating build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_alt_template.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_defvar.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_template.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\linalg.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\list.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\mexutils.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\misc.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  copying spams_wrap\linalg\utils.h -> build\lib.win-amd64-3.7\spams_wrap\linalg
  creating build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\fista.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\groups-graph.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\mexgrouputils.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\project.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\surrogate.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  copying spams_wrap\prox\svm.h -> build\lib.win-amd64-3.7\spams_wrap\prox
  running build_ext
  cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ispams_wrap -Ispa
ms_wrap\linalg -Ispams_wrap\prox -Ispams_wrap\decomp -Ispams_wrap\dictLearn -Id:\rishabh\evaluation\commit-master\venv2\lib\site-packages\numpy\core\include -IC:\Users\Tabinda\AppData\
Local\Programs\Python\Python37\include -Id:\rishabh\evaluation\commit-master\venv2\include -Id:\rishabh\evaluation\commit-master\venv2\include -IC:\Users\Tabinda\AppData\Local\Programs
\Python\Python37\include -IC:\Users\Tabinda\AppData\Local\Programs\Python\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\in
clude -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\includ
e\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Wind
ows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpspams_wrap/spams_wrap.cpp /Fobuild\temp.win-amd64-3.7\Release\spams_wrap/spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -Wun
used-variable -Wno-uninitialized -m64 -fopenmp" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for python-spams
```

**Comment by daducci** [comment]
Hi Tabinda,
first of all, happy new year! 
It looks like a problem with the installation of SPAMS which is the library providing the algorithms for fitting the models to the data. I don't experience with Windows as don't use it, and we typically use Linux os OSX in the lab. Let me ask the other guys and see if someone uses Windows and can zoom in into the problem you faced and help you.
Best,
Ale

**Comment by daducci** [comment]
Did you try having a look at https://github.com/daducci/AMICO/issues/85?

**Comment by sarwart** [comment]
> Did you try having a look at #85?

Hi Alessandro,

Happy new year to you too!

Yes, I did try this but it results in the same error

Tabinda

**Comment by vilsaira** [comment]
Hi Tabinda,

I'm 50-50 Linux/Window user and I might have a solution for you. This will require administrative rights in Windows10 and isn't that straight forward so don't hesitate to ask if you need further help.

Firstly: I was not able to install _python-spams_ to the python3.8.5 installation that I have on my Windows10. I did not try older python versions (2.7) since I think that python2 use should not be encouraged anymore. So to solve this properly, one would need to ask help from the developers of _python-spams_, one of which I unfortunately am not. However, I can give you two options that both worked _for me_:

I tested both options with COMMIT tutorial https://github.com/daducci/COMMIT/wiki/Getting-started and fitting time with **Option 1** was over 10min (there is something wrong with my VM) whereas **Option 2** was 1min 18s. 

**Option 1:** Use a virtual machine e.g. Oracle VM VirtualBox and install Ubuntu/Debian there. This option would have the best support for any problems that you might face later as you get the full power of Linux at your fingertips.

**Option 2:** Use Windows Subsystems for Linux (WSL). This is kinda virtual machine but not a virtual machine. Basically user gets a new command prompt with a chosen Linux flavor within Windows. WSL is intended for quick 'n dirty tests and not for heavy calculations so it might not work well for all purposes. WSL uses Windows to organize tasks for cpu threads which adds additional layer between all processing i.e. it can be slower than a virtual machine but for me it also enabled all 12 threads whereas VM access only 6 cores. This made COMMIT usage considerably faster with WSL than VM! Additionally, WSL is not intended for graphical user interfaces. However, WSL is under constant improvements and gets better all the time, so perhaps it is already _good enough_ for your purposes. These been said:

To install Windows Subsystem for Linux, follow the manual steps here https://docs.microsoft.com/fi-fi/windows/wsl/install-win10#manual-installation-steps and in the final step, choose Ubuntu or Debian (probably newest version is the best choice).

Reboot Win10 as needed and after installation is finished you should have Ubuntu 20.04 LTS in the Win10 startup menu ready to launch. 

On the first start you need to create a new Linux user and set password. Then update Ubuntu and install dependencies:
`sudo apt update`
`sudo apt upgrade`
`sudo apt install git python3-dev python3-virtualenv python3-tk gcc g++ libeigen3-dev r-base libicu-dev libgmp-dev libmpfr-dev mpi-default-bin mpi-default-dev libcgal-dev gmsh libfreetype6-dev libxml2-dev libxslt-dev`

Now you can make changes to python installation (or perhaps create a python virtualenv if you intend to use this Ubuntu CMD for something else too). Assuming, you are using just for COMMIT/AMICO, then run
`pip install --upgrade pip`
`pip install -U pip setuptools`

And now you are ready to install AMICO and COMMIT:
`pip install dmri-amico`
`pip install dmri-commit`

You can locate the files accessible for WSL using command in the Ubuntu CMD
`explorer.exe .`

This opens the Windows Explorer at the location of WSL. Copy paste your data here and allow the Linux user to access this data with following command in Ubuntu CMD
`sudo chown -R your_user_name:your_user_name .`
And now you can use COMMIT. I tested this and it gave same results as VM and I actually didn't see much of a difference compared to the run times in VM.

Ystävällisesti,
 Viljami

**Comment by sarwart** [comment]
Thanks Viljami. Like you said it's not a straightforward solution. I will give it a try.

Thanks again, 

Tabinda
