### ISSUE TITLE
change output directory (python)

### ISSUE THREAD

**Issue by steelec** [daducci/AMICO#21]
Hello there,
First, thanks very much for coding this in python! I am currently testing it with the HCP dataset (1.25mm, 3 shells, 90 dirs in each).

To fit with more generic input output toolchains, would it be possible to add a parameter to ae.save_results to allow the user to explicitly set an output directory to override the RESULTS_path?

e.g., ae.save_results(RESULTS_path="/home/bob/HCP/processing/dwi/NODDI/P001/")

If you like, I would be happy to add and test this.

Cheers,
Chris

**Comment by daducci** [comment]
Hi Chris,

I see what you mean. Do you think this can be equivalently achieved by setting the path you desire when you first the function `Evaluation`?
To date, the policy in AMICO was to specify the folder at the beginning of the script with the `Evaluation` call and then all the processing and produced results are assumed to be relative to this path.

What do you think? Otherwise I'm sure we can find a hack, but I wouldn't like to break the pipeline as it is now.

Best,
Ale

**Comment by steelec** [comment]
Thanks for the quick reply Ale,
Yes, we could add an output_path similarly to the study_path, with the default set to your current default off of the DATA_path. As you suggest, that would keep more in line with your pipeline flow.

by the way, very nice code to read :-)
Chris

**Comment by daducci** [comment]
Thanks! Well, if you have suggestion, you're more than welcome to improve it.
