### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by weijunhuashan** [daducci/AMICO#28]
Dear Daucci:

I am a radiologist in China, and I am now  using  NODDI toolbox for my research.

I tried your AMICO on the demo data, everything is OK. When I used it for my own data, the output file of *_dir,  *_OD are correct, but *_ICVF is very strange, the value of every voxel is 0.99. 
![fit_icvf](https://cloud.githubusercontent.com/assets/20617979/17274354/5b72f628-5710-11e6-9885-fb5aa67ef350.png)

And I processed the data again by original NODDI toolbox, the result is correct now. 

So would you help me to find out what is wrong in it

Thanks

Weijun Tang

**Comment by daducci** [comment]
Dear @weijunhuashan ,

it is indeed strange that some maps are ok (OD) but some others are wrong (ICVF). As it worked on the demo data, I believe there's no installation problem but I suspect it has to do with the scheme file you use. Can you please post here you scheme file as well as the output of AMICO before the fitting? In particular, I'm interested to see if the software interprets correctly the scheme file.

Best,
Alessandro

**Comment by weijunhuashan** [comment]
Dear Daucci:

Here is the scheme I used, and the output of AMICO.

[NODDI_DWI.scheme.txt](https://github.com/daducci/AMICO/files/392654/NODDI_DWI.scheme.txt)

AMICO_SetSubject('fcd', 'jiang_wen_jun');
CONFIG.dwiFilename    = fullfile( CONFIG.DATA_path, 'NODDI_DWI.nii' );
CONFIG.maskFilename   = fullfile( CONFIG.DATA_path, 'roi_mask.nii' );
CONFIG.schemeFilename = fullfile( CONFIG.DATA_path, 'NODDI_DWI.scheme' );
AMICO_LoadData
AMICO_SetModel( 'NODDI' );
AMICO_GenerateKernels( false );
AMICO_ResampleKernels();

-> Loading and setup:
	* Loading DWI...
		- dim    = 100 x 100 x 50 x 90
		- pixdim = 2.500 x 2.500 x 2.500
	* Loading SCHEME...
		- 90 measurements divided in 3 shells (10 b=0)
	* Loading MASK...
		- dim    = 100 x 100 x 50
		- voxels = 109585
   [ DONE ]

-> Generating kernels with model "NODDI" for protocol "fcd":
   [ Kernels already computed. Set "doRegenerate=true" to force regeneration ]

-> Resampling rotated kernels for subject "jiang_wen_jun":
   [=========================] 
   [ 36.5 seconds ]

The scheme file I was obtained used the  " AMICO_fsl2scheme.m".

Thanks!

Weijun

**Comment by daducci** [comment]
Hi @weijunhuashan ,

I think the problem is indeed in the scheme file. Our software assumes b-values are given in `s/mm^2`, while yours seem to be in `s/m^2`, e.g. `7.000E08` instead of `700` and `2.000E09` instead of `2000`. Did you use the original `fsl2scheme` command from Camino (as it seems looking at the header) or our `AMICO_fsl2scheme.m` script?

If you used Camino, then you need to specify the unit using the flag `-bscale` (see [here](http://www0.cs.ucl.ac.uk/research/medic/camino/man/man1/fsl2scheme.1.html)). If instead you used our code, could you please also post you `bvals` and `bvecs` files? This way I can have a look if there was an uncaught exception during the conversion.

Thanks,
Alessandro

**Comment by weijunhuashan** [comment]
Dear Daucci:

Yes. It is the problem. I used the camino with the flag -bscale 1. And everything is correct now.

Thanks a lot for your kindly help.

Weijun

**Comment by daducci** [comment]
Good to know, glad it worked! Thanks for using our software!
Best,
Alessandro
