### ISSUE TITLE
Question: double rescaling ?

### ISSUE THREAD

**Issue by cpresseau** [daducci/AMICO#29]
Hi,

I was looking at the code and was confused about a thing : 
A rescaling is done at line 100 in core.py : 

if ( np.isfinite(hdr['scl_slope']) and np.isfinite(hdr['scl_inter']) and hdr['scl_slope'] != 0 and
            ( hdr['scl_slope'] != 1 or hdr['scl_inter'] != 0 ) ):
            print '\t\t- rescaling data',
            self.niiDWI_img = self.niiDWI_img * hdr['scl_slope'] + hdr['scl_inter']
            print "[OK]"

I thought nibabel was already rescaling the data automatically ?

They say here [http://nipy.org/nibabel/nifti_images.html]  that [_By default, nibabel will take care of this scaling for you, but there may be times that you want to control the data scaling yourself. If so, the next section describes how the scaling works and the nibabel implementation of same_] but also that the values are set back to NaN after the rescaling [_When you load an image, the header scaling values automatically get set to NaN (undefined) to mark the fact that the scaling values have been consumed by the read. The scaling values read from the header on load only appear in the array proxy object._] . If it's the case that means the rescaling is applied twice ? 

Thanks for your help :)

**Comment by daducci** [comment]
Hi @cpresseau ,

I'm actually not very familiar with nibabel, but I kind of remember that I had to manually scale my data because indeed the values in the ndarrays were not scaled. Do you think this may be dependent on a specific (old) version of nibabel?

Btw, according to what you say, it nibabel does scale the data, it then sets the fields `scl_slope` and `scl_inter` to NaN. In our code, we apply the scaling only if the values are finite, so the code should be compatible. Is that correct?

Any help would be appreciated!

Thanks,
Ale

**Comment by daducci** [comment]
Hi @cpresseau ,

any insight about this issue you encountered? Can I close the issue?

Thanks,
Ale
