### ISSUE TITLE
Bug for ae.fit()

### ISSUE THREAD

**Issue by anbai106** [daducci/AMICO#41]
Hello, thanks for your work, I found a problem when fit the noddi model, ae.fit()
the error is 

> Traceback (most recent call last):
  File "amico_noddi_tutorial.py", line 27, in <module>
    ae.fit()
  File "/aramis/home/wen/Applications/Anaconda2/lib/python2.7/site-packages/amico/core.py", line 327, in fit
    MAPs[ix,iy,iz,:], DIRs[ix,iy,iz,:], x, A = self.model.fit( y, dirs.reshape(-1,3), self.KERNELS, self.get_config('solver_params') )
  File "/aramis/home/wen/Applications/Anaconda2/lib/python2.7/site-packages/amico/models.py", line 581, in fit
    A[:,:nWM] = KERNELS['wm'][:,i1,i2,:].T
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`)

So I dig into the source code, and I found the problem is from **amico/models/fit** function:

`i1, i2 = amico.lut.dir_TO_lut_idx( dirs[0] )`

go inside the **dir_TO_lut_idx func**, 

`#i1 = np.round( i1/np.pi*180.0 )
    #i2 = np.round( i2/np.pi*180.0 )`

I just change it to 
`    i1 = np.round( i1/np.pi*180.0 ).astype(int)
    i2 = np.round( i2/np.pi*180.0 ).astype(int)`

and all goes well...

I dont know if this is the problem, can you have a lool at it??? I saw another issue who got the same problem with me.

If it is in the case, I would like to make a pull requests:)

Thanks in advance

Hao

**Comment by davidrs06** [comment]
Hi Hao ! Indeed, this seems to be the solution, although I don't know why it was not an issue before, maybe it is linked to an update in numpy ?

Anyway, nicely spotted, thank you for reporting it quickly, you can proceed with a pull request (you can mention this issue in the pool request as well).

Cheers,
David

**Comment by anbai106** [comment]
Yes maybe because of the numpy update? I even tried numpy.rint(), it should work for numpy version 1.12, but my version is numpy 1.11.1, still it gave me decimals, I think the most safe solution is to add the astype(int), I will do the PR:)

Cheers 
Hao

**Comment by anbai106** [comment]
@davidrs06, I have another question: when you deal with the bval files for NODDI, sometimes the bvals that different shells use are not the exactly same even in one shell, for example, for my data, i used 3 shelles**(300, 700, 2200)**, but in the bval file, we have b0 bval not 0, but instead 5, and shell(300) with 295, 300, 305, shell(700) and 2200 with the same philosophy, I know that in Noddi matlab toolbox, when they count the number of b0 images and the number of shells, they count exactly the well-defined values( 0, 300, 700, 2200), 

so the result of number of b0 is 0, the number of shells will be more than 3, maybe 11,

 You see what I mean?  How do you deal with this kind of stuff? You let the users to correct the bval files?

Cheers Hao

**Comment by davidrs06** [comment]
It depends on what you want to do. If you don't mind having rounded values used to compute the response functions, you can create a scheme with 3 shells and a b0 (0, 300, 700, 2200). There's a function called [fsl2scheme](https://github.com/daducci/AMICO/blob/master/amico/util.py) that you can use setting the `bStep` parameter to the list of b-values that you want. This will create the scheme file that you need to use as input for AMICO after.

If you want the true b-value to be used then just set `b0_thr = 10` in the function `load_data( )`. This will create the response functions for a b0 of 0 instead of 5, and all the dwi with their correct b-value (295,300,305, etc..). As a consequence, you will end up with a much larger lookup table, but generated with the b-values that correspond to your acquisition.

Cheers,
David

**Comment by davidrs06** [comment]
Thank you for the pull request, I just merged it and everything seems to be ok now. Let us know if you run into any other bug or if you have suggestions for improvements. Thanks for your contribution !

Best regards,
David
