### ISSUE TITLE
error when import amico

### ISSUE THREAD

**Issue by jz219** [daducci/AMICO#53]
hello! I met this problem when I tried to import amico, and don't know the reason. Could you tell where this module named 'core' should be? I found several folder but none of them contained 'Evaluation'.

$ python
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import amico
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../anaconda/lib/python3.6/site-packages/amico/__init__.py", line 1, in <module>
    from core import Evaluation
ModuleNotFoundError: No module named 'core'

thank you!

**Comment by davidrs06** [comment]
Hi ! It seems that the issue is due to the current implementation of AMICO, which is compatible with python 2.7 and not the last version you have installed. Could you try creating a conda environment with python 2.7 as described [here](https://conda.io/docs/user-guide/tasks/manage-python.html) (set version to 2.7 instead of 3.6). Then install amico, dipy and nibabel and try running the tutorial again. Let me know how this goes.

Cheers,
David

**Comment by pangyuteng** [comment]
I have encountered the same issue, switch to py 2.7 works. Thank you!
