### ISSUE TITLE
volume fractions in the CylinderZeppelinBall model

### ISSUE THREAD

**Issue by barakovic** [daducci/AMICO#54]
In the CylinderZeppelinBall model the volume fraction of the Ball is not considered in the normalization of the maps. 

```
 # return estimates
 f1 = x[ :(nD*n1) ].sum()
 f2 = x[ (nD*n1):(nD*(n1+n2)) ].sum()
 v = f1 / ( f1 + f2 + 1e-16 )
```

Is there a reason? It is useful to have consistent maps with `COMMIT`.

**Comment by davidrs06** [comment]
It’s from the definition of the ICVF for ActiveAx in the AMICO paper (equation 6), which corresponds to the definition originally given by Alexander for ActiveAx (equation 3).

The definition for NODDI is also different...

**Comment by davidrs06** [comment]
Depends on what we want to do. In terms of logic, I think it would make more sense to have the ICVF really mean the fraction with respect to the whole volume (normalizing by `x.sum()`, which would include the isotropic compartment, but also the dot compartment when using ex-vivo data for example, or any compartment included in the model), but in that case the definition will not match the definitions in ActiveAx and NODDI models anymore. And that was the original idea right, to have maps that match the original ActiveAx and NODDI models ? What do you think @daducci ?

**Comment by daducci** [comment]
I agree with you that this comes from the definition of the ICVF in the respective models, we cannot change that (otherwise we'd break the compatibility with those models). What about adding a flag, e.g. `maps_consider_all_compartments`, to the function to export the maps for selecting whether to use (i) the original definition of the maps or (ii) normalize by all the compartments?
